include_guard(GLOBAL)
find_package(ICU REQUIRED COMPONENTS uc)
find_path(PCRE2_INCLUDE_DIR pcre2.h HINTS "$ENV{CONDA_PREFIX}/include")
find_library(PCRE2_LIBRARY NAMES pcre2-8 HINTS "$ENV{CONDA_PREFIX}/lib")
if (NOT PCRE2_INCLUDE_DIR OR NOT PCRE2_LIBRARY)
    message(FATAL_ERROR "Install PCRE2 8-bit development files or set CMAKE_PREFIX_PATH to their prefix.")
endif()
add_library(qwen_tokenizer_dependencies INTERFACE)
target_include_directories(qwen_tokenizer_dependencies INTERFACE "${PCRE2_INCLUDE_DIR}")
target_link_libraries(qwen_tokenizer_dependencies INTERFACE "${PCRE2_LIBRARY}" ICU::uc)
